### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by ayushmankoley** [PratyayDhond/Kindle-Highlights-extractor#2] opened 2023-10-02 13:40 UTC
Hey would love to contribute please assign

**Comment by PratyayDhond** [comment] 2023-10-02 14:21
What changes do you plan to make in the readme.md file? Please do specify that in reply comment and in the pull request when you submit it.

**Comment by Sayak-Bhunia** [comment] 2023-10-02 16:33
hey please assign me this issue. i am willing to create a readme file that will guide the users about your project and the process of using it.

**Comment by pathakharsh123** [comment] 2023-10-02 21:00
please assign me this issue

**Comment by PratyayDhond** [comment] 2023-10-03 00:03
@Sayak-Bhunia I see you have already created a pull request, I will assign this to you for this time, from next time wait till the issue is assigned to you.

and @pathakharsh123 try creating new issue for the repo, it doesn't necessarily have to be documentation, you can even contribute to the code.

**Closed** 2023-10-03 00:08 UTC
Labels: documentation, good first issue
